[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true

[build]
rustflags = ["-C", "link-args=-L/usr/local/lib"]

[dependencies]
dotenv = "0.15"          # For loading environment variables
log = "0.4"              # For logging
env_logger = "0.10"      # Environment-based logging configuration
actix-web = "4.0"
actix-multipart = "0.4"
futures = "0.3"
actix-cors = "0.6"       # CORS for frontend-backend communication
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "uuid", "postgres", "chrono"] }
uuid = { version = "1.0", features = ["v4", "serde", "fast-rng"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
postgres = "0.19"
thiserror = "1.0"  # Add this line to include `thiserror`
bcrypt = "0.12"
jsonwebtoken = "9.3.0"
chrono = "0.4"
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
supabase = "0.0.0"
tokio = { version = "1", features = ["full"] }
tokio-macros = "1.0"
futures-util = "0.3"
mime_guess = "2.0"